version: "3.8"
services:
  strapi:
    build: ./strapi
    container_name: strapi
    image: modern-strapi:latest
    restart: unless-stopped
    env_file:
      - ./strapi/.env
    volumes:
      - ./strapi:/app
      - strapi-uploads:/app/public/uploads
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    image: modern-nextjs:latest
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - strapi
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - strapi
    networks:
      - app-network

volumes:
  pgdata:
  strapi-uploads:

networks:
  app-network:
