version: "3.8"

services:
  strapi:
    build: ./strapi
    container_name: strapi
    image: modern-strapi:latest
    restart: unless-stopped
    env_file:
      - ./strapi/.env
    volumes:
      - ./strapi:/app
      - strapi-uploads:/app/public/uploads
    depends_on:
      - postgres
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`yourdomain.com`) && PathPrefix(`/api`)"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    image: modern-nextjs:latest
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - strapi
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yourdomain.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

volumes:
  pgdata:
  strapi-uploads:

networks:
  app-network:
